export const data = {
    users: [
        {
            _id: "user1",
            username: "john_doe",
            password: "hashedpassword",
            email: "john@example.com",
            joinDate: "2023-05-15",
            lastLogin: "2024-03-19",
        },
    ],
    boards: [
        {
            _id: "board1",
            boardName: "Development Board",
            columns: ["column1", "column2"],
        },
        {
            _id: "board2",
            boardName: "Development web",
            columns: ["column1", "column3"],
        },
        {
            _id: "board3",
            boardName: "Development mobile",
            columns: ["column2", "column3"],
        },
    ],
    columns: [
        {
            _id: "column1",
            board: "board1",
            columnName: "To Do",
            columnOrder: 1,
        },
        {
            _id: "column2",
            board: "board2",
            columnName: "Doing",
            columnOrder: 2,
        },
        {
            _id: "column3",
            board: "board1",
            columnName: "Done",
            columnOrder: 3,
        },
    ],
    tasks: [
        {
            _id: "task1",
            column: "column1",
            user: "user1",
            taskName: "WireFrame Homepage",
            description: "Create wireFrame for the homepage design.",
            deadline: "2024-04-15",
            priority: "High",
            status: "Doing",
            assignedTo: "user1",
            starred: true,
            created_at: "Nov, 12/2023"
        },
        {
            _id: "task9",
            column: "column1",
            user: "user1",
            taskName: "WireFrame Homepage",
            description: "Create wireFrame for the homepage design.",
            deadline: "2024-04-15",
            priority: "High",
            status: "Doing",
            assignedTo: "user1",
            starred: true,
            created_at: "Nov, 12/2023"
        },
        {
            _id: "task8",
            column: "column1",
            user: "user1",
            taskName: "WireFrame Homepage",
            description: "Create wireFrame for the homepage design.",
            deadline: "2024-04-15",
            priority: "High",
            status: "Doing",
            assignedTo: "user1",
            starred: false,
            created_at: "Nov, 12/2023"
        },
        {
            _id: "task2",
            column: "column1",
            user: "user1",
            taskName: "WireFrame Homepage",
            description: "Create wireFrame for the homepage design.",
            deadline: "2024-04-15",
            priority: "medium",
            status: "Done",
            assignedTo: "user1",
            starred: false,
            created_at: "Nov, 12/2023"
        },
        {
            _id: "task7",
            column: "column1",
            user: "user1",
            taskName: "WireFrddddddddame Homepage",
            description: "Create wireFrame for the homepage design.",
            deadline: "2024-04-15",
            priority: "low",
            status: "ToDo",
            assignedTo: "user1",
            starred: false,
            created_at: "Nov, 12/2023"
        },
        {
            _id: "task4",
            column: "column1",
            user: "user1",
            taskName: "WireFrame Homepage",
            description: "Create wireFrame for the homepage design.",
            deadline: "2024-04-15",
            priority: "low",
            status: "ToDo",
            assignedTo: "user1",
            starred: false,
            created_at: "Nov, 12/2023"
        },
        {
            _id: "task5",
            column: "column1",
            user: "user1",
            taskName: "WireFrame Homepage",
            description: "Create wireFrame for the homepage design.",
            deadline: "2024-04-15",
            priority: "low",
            status: "ToDo",
            assignedTo: "user1",
            starred: false,
            created_at: "Nov, 12/2023"
        },
        {
            _id: "task6",
            column: "column1",
            user: "user1",
            taskName: "WireFrame Homepage",
            description: "Create wireFrame for the homepage design.",
            deadline: "2024-04-15",
            priority: "low",
            status: "ToDo",
            assignedTo: "user1",
            starred: false,
            created_at: "Nov, 12/2023"
        },
    ],
};
