import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/Provider/authProviders"
import { Session } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, session
}: {
  children: React.ReactNode, session: Session | null
}) {
  return (
    <html lang="en">
      <body className={inter.className + " bg-[#252729]"}>
        <AuthProvider session={session}>
          {children}
        </AuthProvider>

      </body>
    </html>
  );
}
